"""sprint_id

Revision ID: 0a6bb343ef87
Revises: 3ab2f1fb4a1b
Create Date: 2026-07-23 17:13:02.975846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6bb343ef87'
down_revision: Union[str, Sequence[str], None] = '3ab2f1fb4a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('sprint_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'sprint_id')
    # ### end Alembic commands ###
