"""operations

Revision ID: 3ab2f1fb4a1b
Revises: 6ed10f301d60
Create Date: 2026-07-23 10:40:25.503014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ab2f1fb4a1b"
down_revision: Union[str, Sequence[str], None] = "6ed10f301d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    operation_enum = postgresql.ENUM("BUY", "SELL", name="operations")
    operation_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "moves",
        sa.Column(
            "operation", sa.Enum("BUY", "SELL", name="operations"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("moves", "operation")
    op.execute("drop type public.operations;")
    # ### end Alembic commands ###
