"""initial migrate

Revision ID: 5a157ad8d8a0
Revises: 
Create Date: 2026-06-27 20:48:57.705491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a157ad8d8a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('isin', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('issuevalue', sa.Integer(), nullable=False),
    sa.Column('coupondate', sa.Date(), nullable=False),
    sa.Column('recorddate', sa.Date(), nullable=False),
    sa.Column('startdate', sa.Date(), nullable=False),
    sa.Column('initialfacevalue', sa.Integer(), nullable=False),
    sa.Column('facevalue', sa.Integer(), nullable=False),
    sa.Column('faceunit', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('valueprc', sa.Float(), nullable=False),
    sa.Column('value_rub', sa.Float(), nullable=False),
    sa.Column('secid', sa.String(length=256), nullable=False),
    sa.Column('primary_boardid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    # ### end Alembic commands ###
