"""moves

Revision ID: 6ed10f301d60
Revises: 0ad8f57d2ea5
Create Date: 2026-07-22 20:09:58.592080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed10f301d60'
down_revision: Union[str, Sequence[str], None] = '0ad8f57d2ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candle_id', sa.UUID(), nullable=False),
    sa.Column('previous_id', sa.UUID(), nullable=True),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
