"""move_fields

Revision ID: 94be6ff80373
Revises: 0a6bb343ef87
Create Date: 2026-07-23 18:32:10.959290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94be6ff80373'
down_revision: Union[str, Sequence[str], None] = '0a6bb343ef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('summ', sa.Float(), nullable=False))
    op.add_column('moves', sa.Column('remain', sa.Float(), nullable=False))
    op.add_column('moves', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('moves', 'total')
    op.drop_column('moves', 'current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('moves', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('moves', 'price')
    op.drop_column('moves', 'count')
    op.drop_column('moves', 'remain')
    op.drop_column('moves', 'summ')
    # ### end Alembic commands ###
