"""securities

Revision ID: bcc7840cc1be
Revises: dc6ca6b13853
Create Date: 2026-06-28 20:20:02.264489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcc7840cc1be'
down_revision: Union[str, Sequence[str], None] = 'dc6ca6b13853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('secid', sa.String(length=256), nullable=False),
    sa.Column('description', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.PrimaryKeyConstraint('secid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    # ### end Alembic commands ###
