"""add_info

Revision ID: bfa93be2637e
Revises: bcc7840cc1be
Create Date: 2026-06-30 20:30:25.244994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfa93be2637e'
down_revision: Union[str, Sequence[str], None] = 'bcc7840cc1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'info')
    # ### end Alembic commands ###
