"""tops

Revision ID: f6dafcec108a
Revises: 94be6ff80373
Create Date: 2026-09-27 09:55:52.846580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dafcec108a'
down_revision: Union[str, Sequence[str], None] = '94be6ff80373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_today',
    sa.Column('secid', sa.String(length=256), nullable=False),
    sa.Column('boardid', sa.String(length=256), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('biddepth', sa.Float(), nullable=True),
    sa.Column('offer', sa.Float(), nullable=True),
    sa.Column('offerdepth', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('biddeptht', sa.Integer(), nullable=False),
    sa.Column('offerdeptht', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('last', sa.Float(), nullable=False),
    sa.Column('lastchange', sa.Float(), nullable=False),
    sa.Column('lastchangeprcnt', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=False),
    sa.Column('waprice', sa.Float(), nullable=False),
    sa.Column('lastcngtolastwaprice', sa.Float(), nullable=False),
    sa.Column('waptoprevwapriceprcnt', sa.Float(), nullable=False),
    sa.Column('waptoprevwaprice', sa.Float(), nullable=False),
    sa.Column('closeprice', sa.Float(), nullable=False),
    sa.Column('marketpricetoday', sa.Float(), nullable=False),
    sa.Column('marketprice', sa.Float(), nullable=False),
    sa.Column('lasttoprevprice', sa.Float(), nullable=False),
    sa.Column('numtrades', sa.Integer(), nullable=False),
    sa.Column('voltoday', sa.Integer(), nullable=False),
    sa.Column('valtoday', sa.Integer(), nullable=False),
    sa.Column('valtoday_usd', sa.Integer(), nullable=False),
    sa.Column('etfsettleprice', sa.Float(), nullable=False),
    sa.Column('tradingstatus', sa.String(length=256), nullable=False),
    sa.Column('updatetime', sa.Time(), nullable=False),
    sa.Column('lastbid', sa.Float(), nullable=False),
    sa.Column('lastoffer', sa.Float(), nullable=False),
    sa.Column('lcloseprice', sa.Float(), nullable=False),
    sa.Column('lcurrentprice', sa.Float(), nullable=False),
    sa.Column('marketprice2', sa.Float(), nullable=False),
    sa.Column('numbids', sa.Float(), nullable=False),
    sa.Column('numoffers', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('highbid', sa.Float(), nullable=False),
    sa.Column('lowoffer', sa.Float(), nullable=False),
    sa.Column('priceminusprevwaprice', sa.Float(), nullable=False),
    sa.Column('openperiodprice', sa.Float(), nullable=False),
    sa.Column('seqnum', sa.Float(), nullable=False),
    sa.Column('systime', sa.DateTime(), nullable=False),
    sa.Column('closingauctionprice', sa.Float(), nullable=False),
    sa.Column('closingauctionvolume', sa.Float(), nullable=False),
    sa.Column('issuecapitalization', sa.Float(), nullable=False),
    sa.Column('issuecapitalization_updatetime', sa.Time(), nullable=False),
    sa.Column('etfsettlecurrency', sa.String(length=256), nullable=False),
    sa.Column('valtoday_rur', sa.Float(), nullable=False),
    sa.Column('tradingsession', sa.String(length=256), nullable=False),
    sa.Column('trendissuecapitalization', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('secid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_today')
    # ### end Alembic commands ###
